# Generated by Django 3.0 on 2021-10-02 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_photo', models.TextField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_in_english', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на английском')),
                ('name_in_russian', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на русском')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='', verbose_name='постер')),
                ('slogan', models.TextField(blank=True, null=True, verbose_name='слоган')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('released', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('trailer', models.URLField(blank=True, null=True, verbose_name='ссылка на трейлер')),
                ('duration', models.IntegerField(blank=True, default=0, null=True, verbose_name='Длительность')),
                ('minimum_age', models.IntegerField(blank=True, null=True, verbose_name='Минимальный возраст')),
                ('type_picture', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Film'), (1, 'Serial'), (2, 'Cartoon'), (3, 'Anime'), (4, 'animated-series')], null=True, verbose_name='Тип картины')),
                ('premiere_in_Russia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Премьера в России')),
                ('rating_kinopoisk', models.FloatField(blank=True, null=True, verbose_name='рейтинг от кинопоиска')),
                ('rating_imdb', models.FloatField(blank=True, null=True, verbose_name='рейтинг от IMDB')),
                ('facts', models.TextField(blank=True, null=True, verbose_name='список фактов')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания картины')),
                ('country', models.ManyToManyField(to='objects.Country')),
                ('directors', models.ManyToManyField(to='objects.Director')),
                ('genres', models.ManyToManyField(to='objects.Genre')),
                ('starring', models.ManyToManyField(to='objects.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='SimilarPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_pictures', to='objects.Picture')),
                ('similar_picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_picture', to='objects.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Постер подборки')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('views', models.IntegerField(default=0, verbose_name='Кол-во просмотров подборки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pictures', models.ManyToManyField(to='objects.Picture')),
            ],
        ),
    ]
