# Generated by Django 3.0 on 2021-09-19 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_in_english', models.CharField(max_length=255, verbose_name='Название на английском')),
                ('name_in_russian', models.CharField(max_length=255, verbose_name='Название на русском')),
                ('poster', models.URLField(verbose_name='ссылка на постер')),
                ('description', models.TextField(verbose_name='описание')),
                ('released', models.IntegerField(verbose_name='Год выпуска')),
                ('trailer', models.URLField(verbose_name='ссылка на трейлер')),
                ('duration', models.TimeField(verbose_name='Длительность')),
                ('minimum_age', models.IntegerField(verbose_name='Минимальный возраст')),
                ('type_picture', models.PositiveSmallIntegerField(choices=[(0, 'Film'), (1, 'Serial'), (2, 'Cartoon'), (3, 'Anime')])),
                ('premiere_in_Russia', models.CharField(max_length=255, verbose_name='Премьера в России')),
                ('rating_kinopoisk', models.FloatField(verbose_name='рейтинг от кинопоиска')),
                ('rating_imdb', models.FloatField(verbose_name='рейтинг от IMDB')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country', models.ManyToManyField(to='objects.Country')),
                ('directors', models.ManyToManyField(to='objects.Director')),
                ('genres', models.ManyToManyField(to='objects.Genre')),
                ('starring', models.ManyToManyField(to='objects.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='ссылка на кадр')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('views', models.IntegerField(verbose_name='Кол-во просмотров подборки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pictures', models.ManyToManyField(to='objects.Picture')),
            ],
        ),
    ]
