# Generated by Django 3.0 on 2021-10-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilation',
            name='main_genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='objects.Genre'),
            preserve_default=False,
        ),
    ]
