# Generated by Django 3.0 on 2021-09-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='duration',
            field=models.IntegerField(verbose_name='Длительность'),
        ),
    ]
