# Generated by Django 3.0 on 2021-10-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_compilation_main_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compilation',
            name='main_genre',
        ),
        migrations.AddField(
            model_name='compilation',
            name='main_genre',
            field=models.ManyToManyField(to='objects.Genre'),
        ),
    ]
