# Generated by Django 3.0 on 2021-10-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20211002_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilation',
            name='main_genre_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
