# Generated by Django 3.0 on 2021-10-03 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_compilation_main_genre_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='genres',
            field=models.ManyToManyField(related_name='pictures', to='objects.Genre'),
        ),
        migrations.CreateModel(
            name='PictureFrames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Кадр')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.Picture')),
            ],
        ),
    ]
