# Generated by Django 3.0 on 2021-09-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20210921_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='name_in_english',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name_in_russian',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на русском'),
        ),
    ]
