# Generated by Django 3.0 on 2021-09-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_auto_20210921_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='minimum_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальный возраст'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='poster',
            field=models.TextField(blank=True, null=True, verbose_name='ссылка на постер'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='premiere_in_Russia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Премьера в России'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='rating_imdb',
            field=models.FloatField(blank=True, null=True, verbose_name='рейтинг от IMDB'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='rating_kinopoisk',
            field=models.FloatField(blank=True, null=True, verbose_name='рейтинг от кинопоиска'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='released',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='trailer',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на трейлер'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='type_picture',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Film'), (1, 'Serial'), (2, 'Cartoon'), (3, 'Anime')], null=True),
        ),
    ]
