# Generated by Django 3.0 on 2021-10-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_auto_20211003_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='similar_picture',
            field=models.ManyToManyField(related_name='_picture_similar_picture_+', to='objects.Picture'),
        ),
    ]
