# Generated by Django 3.0 on 2021-09-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_auto_20210921_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='url_photo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
