# Generated by Django 3.0 on 2021-09-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_actor_url_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='facts',
            field=models.TextField(default=1, verbose_name='список фактов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='slogan',
            field=models.TextField(default=1, verbose_name='слоган'),
            preserve_default=False,
        ),
    ]
