# Generated by Django 3.0 on 2021-10-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_compilation_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='kinopoisk_id',
            field=models.IntegerField(default=1, verbose_name='айди кинопоиска'),
            preserve_default=False,
        ),
    ]
