# Generated by Django 3.0 on 2021-09-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_auto_20210922_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='cartoon',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
