# Generated by Django 3.0 on 2021-10-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_picture_kinopoisk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(default=1, upload_to='genres/'),
            preserve_default=False,
        ),
    ]
