# Generated by Django 3.0 on 2021-09-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_picture_cartoon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='cartoon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='picture',
            name='slogan',
            field=models.TextField(blank=True, null=True, verbose_name='слоган'),
        ),
    ]
