# Generated by Django 3.0 on 2021-10-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_genre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='banner',
            field=models.ImageField(default=1, upload_to='banners/'),
            preserve_default=False,
        ),
    ]
