# Generated by Django 3.0 on 2021-10-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0011_picture_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='banner',
            new_name='preview',
        ),
    ]
