# Generated by Django 3.0 on 2021-09-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0011_auto_20210923_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilation',
            name='pictures',
            field=models.ManyToManyField(to='objects.Picture'),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='poster',
            field=models.TextField(blank=True, null=True, verbose_name='ссылка на постер подборки'),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='views',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во просмотров подборки'),
        ),
    ]
