# Generated by Django 3.0 on 2021-09-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_auto_20210923_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='facts',
            field=models.TextField(blank=True, null=True, verbose_name='список фактов'),
        ),
    ]
