# Generated by Django 3.0 on 2021-10-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_auto_20211012_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilation',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
