# Generated by Django 3.0 on 2021-09-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_auto_20210923_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilation',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Кол-во просмотров подборки'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
