# Generated by Django 3.0 on 2021-11-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0014_auto_20211012_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='url_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='picture',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
