# Generated by Django 3.0 on 2021-11-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0015_auto_20211126_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilation',
            name='type_collections',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Film'), (1, 'Serial'), (2, 'Cartoon'), (3, 'Anime'), (4, 'animated-series')], null=True, verbose_name='Тип подборки'),
        ),
    ]
