# Generated by Django 3.0 on 2021-09-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0015_auto_20210924_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilation',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='постер подборки'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='постер'),
        ),
        migrations.DeleteModel(
            name='Frame',
        ),
    ]
