# Generated by Django 3.0 on 2021-11-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0016_compilation_type_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='СollectionСategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('keywords', models.TextField()),
                ('collections', models.ManyToManyField(to='objects.Compilation')),
            ],
        ),
    ]
