# Generated by Django 3.0 on 2021-11-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0017_сollectionсategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='сollectionсategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка категории'),
        ),
    ]
