# Generated by Django 3.0 on 2021-11-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0018_сollectionсategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='сollectionсategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
